services:
  db_patitas:
    image: postgres:15-alpine
    container_name: postgres_patitas
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}        
      POSTGRES_USER: ${POSTGRES_USER}    
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
    volumes:
      - pgdata:/var/lib/postgresql/data

 
  app_patitas:
    build: .
    container_name: app_patitas_web
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}" 
    depends_on:
      - db_patitas
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_patitas:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

volumes:
  pgdata: